# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180813_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
