# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20180813_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'get_latest_by': 'createdDate'},
        ),
        migrations.AlterField(
            model_name='twitterprofile',
            name='imageURI',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
