# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20180813_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 22, 52, 37, 128338, tzinfo=utc)),
        ),
    ]
