# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20180813_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
